### ISSUE TITLE
depth images are empty?

### ISSUE THREAD

**Issue by chenying6** [YoungXIAO13/ObjectPoseEstimationDatasets#1]
Thank you for your contribution!!!
However, I have one question when I have downloaded the LM, LMO datasets, all the images in the depth folders are black which are filled with 0.
I don't know why and how to solve this problem??

**Comment by YoungXIAO13** [comment]
Hi,
I think the zeros in depth map represents the zone where the estimated depth is invalid and they should be ignored.
