### ISSUE TITLE
Difference betweeen generated nocs and normal.

### ISSUE THREAD

**Issue by EricLWJ** [YoungXIAO13/ObjectPoseEstimationDatasets#12]
Hi,
I have ran the render_grid.py with the LM dataset and it generated a depth.png, nocs.png and normal.png. I would like to know what is the differance between the nocs.png and normal.png as both seem to have color?

I am trying to create the coord.png from the NOCS repo (https://github.com/hughw19/NOCS_CVPR2019) and was led here to create it. The coord.png looks to have the nocs map layed over an camera scene with rgb or white background with multiple categories. So far using the render_grid.py, the nocs.png generated only contain one angle made from a obj file. The nocs.png is also not fitted into a camera scene from the LM dataset. How else should I go about achieving the coord.png required by the NOCS repo?

I would also like to confirm, to create the nocs, the --dataset_format that i should be using in the render_grid should be "BOP" right?

Thanks, looking forward to your reply.

**Comment by YoungXIAO13** [comment]
Hi, 
The rendering code in this repo was written years ago and I recommend you to take a look at the nocs generation code provided by the original author in their repo: https://github.com/hughw19/NOCS_CVPR2019#rendering-nocs-map-using-blender-279b

**Comment by EricLWJ** [comment]
Thanks for the quick reply,
The code in the NOCS repo (nocs_map_cube.py) only generates a nocs color cube for me. How does it relate to getting the coord.png?
