### ISSUE TITLE
The version of blender

### ISSUE THREAD

**Issue by KzZheng** [YoungXIAO13/ObjectPoseEstimationDatasets#4]
Hi, when I run the render_grid.py, it shows the issue:
`AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'`, which happens at line 97 in render_utils.py.
My blender version is 2.82, is this wrong?

**Comment by YoungXIAO13** [comment]
Hi, I'm not sure about whether this problem comes from the blender version.
But this code is mainly used to set the render image in "RGBA" mode, a workaround might be provided [here](https://blender.stackexchange.com/questions/9085/how-to-set-color-mode-to-rgba-using-script)

**Comment by KzZheng** [comment]
Cool, I fix this, but a new issue happens. `'RenderSettings' object has no attribute 'layers'`, line 134, render_utils.py. So what's the version of your blender?

**Comment by YoungXIAO13** [comment]
Right, maybe you could check this [install steps](https://github.com/YoungXIAO13/PoseFromShape#dependencies)
Apprently I used Blender 2.77 in my previous project when I wrote the rendering code.

**Comment by Iven-Wu** [comment]
Hi, I came to the same 'alpha_mode' problems too. Would you mind telling me how to deal with that?

**Comment by nattaran** [comment]
the same issue

**Comment by daixiangzi** [comment]
+1
